apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: webchat-backend
  name: profile-images-pvc
  namespace: webchat
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: standard