apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: webchat-backend
  name: webchat-backend
  namespace: webchat
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webchat-backend
  template:
    metadata:
      labels:
        app: webchat-backend
    spec:
      containers:
        - name: webchat-backend
          image: harllemnascimento/webchat-backend:latest
          env:
            - name: DB_NAME
              value: webchat
            - name: DB_HOST
              value: webchat-database
            - name: DB_PORT
              value: "3306"
            - name: MAX_FILE_SIZE
              value: "10MB"
            - name: MAX_REQUEST_SIZE
              value: "10MB"
            - name: IMAGES_PATH
              value: "/app/images/"
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: secrets
                  key: jwt-secret
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: secrets
                  key: db-user
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: secrets
                  key: db-pass
          ports: 
            - containerPort: 8080
          volumeMounts:
            - name: profile-images-volume
              mountPath: /app/images
      volumes:
        - name: profile-images-volume
          persistentVolumeClaim:
            claimName: profile-images-pvc