apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: webchat-image-worker
  name: webchat-image-worker
  namespace: webchat
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webchat-image-worker
  template:
    metadata:
      labels:
        app: webchat-image-worker
    spec:
      containers:
        - name: webchat-image-worker
          image: harllemnascimento/rc-image-worker:v1
          imagePullPolicy: Always
          env:
            - name: PORT
              value: "8080"

            - name: DB_NAME
              value: webchat

            - name: DB_HOST
              value: webchat-database

            - name: DB_PORT
              value: "3306"

            - name : RABBITMQ_HOST
              value: "webchat-rabbitmq"

            - name : USER_SERVICE
              value: "webchat-svc-user"

            - name : DB_USERNAME
              value: "root"

            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: secrets
                  key: db-root-pass
          ports:
            - containerPort: 8080
          resources:
            limits:
              memory: "1.5Gi"
              cpu: "2"
            requests:
              memory: "250Mi"
              cpu: "0.5"