apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: webchat-proxy
  name: webchat-proxy
  namespace: webchat
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webchat-proxy
  template:
    metadata:
      labels:
        app: webchat-proxy
    spec:
      containers:
        - name: webchat-proxy
          image: harllemnascimento/rc-proxy:v1
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          resources:
            limits:
              memory: "1Gi"
              cpu: "2"
            requests:
              memory: "200Mi"
              cpu: "0.5"
