-- MySQL Script generated by MySQL Workbench
-- Sun Jun 18 01:45:07 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema webchat
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema webchat
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `webchat` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `webchat` ;

-- -----------------------------------------------------
-- Table `webchat`.`profile_image`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `webchat`.`profile_image` (
  `id` BINARY(16) NOT NULL,
  `user_id` BIGINT NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `UK_1m51rfssuj7hyuo2lteq4ubad` (`user_id` ASC) VISIBLE,
  CONSTRAINT `FKsbiasd8poxtjj1pr99oi0rrx5`
    FOREIGN KEY (`user_id`)
    REFERENCES `webchat`.`users` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `webchat`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `webchat`.`users` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `formal_name` VARCHAR(100) NOT NULL,
  `password` VARCHAR(70) NOT NULL,
  `user_name` VARCHAR(30) NOT NULL,
  `profile_image_id` BINARY(16) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `UK_4unapofvpijp79n4j3sheoun7` (`profile_image_id` ASC) VISIBLE,
  CONSTRAINT `FKgjuyyw52s3xe61nrl2l6q1j6y`
    FOREIGN KEY (`profile_image_id`)
    REFERENCES `webchat`.`profile_image` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `webchat`.`messages`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `webchat`.`messages` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `created_at` DATETIME(6) NULL DEFAULT NULL,
  `message` TEXT NOT NULL,
  `readed` BIT(1) NULL DEFAULT NULL,
  `status` TINYINT NOT NULL,
  `receiver_id` BIGINT NULL DEFAULT NULL,
  `sender_id` BIGINT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `FKt05r0b6n0iis8u7dfna4xdh73` (`receiver_id` ASC) VISIBLE,
  INDEX `FK4ui4nnwntodh6wjvck53dbk9m` (`sender_id` ASC) VISIBLE,
  CONSTRAINT `FK4ui4nnwntodh6wjvck53dbk9m`
    FOREIGN KEY (`sender_id`)
    REFERENCES `webchat`.`users` (`id`),
  CONSTRAINT `FKt05r0b6n0iis8u7dfna4xdh73`
    FOREIGN KEY (`receiver_id`)
    REFERENCES `webchat`.`users` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 32
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `webchat`.`refresh_tokens`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `webchat`.`refresh_tokens` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `token` VARCHAR(200) NOT NULL,
  `user_id` BIGINT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `FK1lih5y2npsf8u5o3vhdb9y0os` (`user_id` ASC) VISIBLE,
  CONSTRAINT `FK1lih5y2npsf8u5o3vhdb9y0os`
    FOREIGN KEY (`user_id`)
    REFERENCES `webchat`.`users` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 24
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
