version: '3.7'

services:
  database:
    environment:
      - MYSQL_USER=
      - MYSQL_PASSWORD=
      - MYSQL_ROOT_PASSWORD=

  backend:
    environment:
      - DB_USERNAME=
      - DB_PASSWORD=
      - JWT_SECRET=