apiVersion: v1
kind: Service
metadata:
  labels:
    app: webchat-api-gateway
  name: webchat-svc-api-gateway
  namespace: webchat
spec:
  selector:
    app: webchat-api-gateway
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP