apiVersion: v1
kind: Service
metadata:
  labels:
    app: webchat-message
  name: webchat-svc-message
  namespace: webchat
spec:
  selector:
    app: webchat-message
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP