apiVersion: v1
kind: Service
metadata:
  labels:
    app: webchat-user
  name: webchat-svc-user
  namespace: webchat
spec:
  selector:
    app: webchat-user
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP