apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: webchat-backend
  name: webchat-backend
  namespace: webchat
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webchat-backend
  template:
    metadata:
      labels:
        app: webchat-backend
    spec:
      containers:
        - name: webchat-backend
          image: harllemnascimento/webchat-backend:latest
          env:
            - name: DB_NAME
              value: webchat
            - name: DB_HOST
              value: webchat-database
            - name: DB_PORT
              value: "3306"
            - name: MAX_FILE_SIZE
              value: "10MB"
            - name: MAX_REQUEST_SIZE
              value: "10MB"
            - name: IMAGES_PATH
              value: "/app/profile-images/"
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: secrets
                  key: jwt-secret
            - name: DB_USERNAME
              value: root
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: secrets
                  key: db-root-pass
          ports: 
            - containerPort: 8080
          volumeMounts:
            - name: image-volume
              mountPath: /app/profile-images
          resources:
            limits:
              memory: "8Gi"
              cpu: "6"
            requests:
              memory: "1Gi"
              cpu: "1"
      volumes:
        - name: image-volume
          persistentVolumeClaim:
            claimName: profile-images-pvc