apiVersion: v1
kind: Service
metadata:
  labels:
    app: webchat-backend
  name: webchat-backend
  namespace: webchat
spec:
  selector:
    app: webchat-backend
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: NodePort