apiVersion: v1
kind: Service
metadata:
  labels:
    app: webchat-auth-database
  name: webchat-auth-database
  namespace: webchat
spec:
  selector:
    app: webchat-auth-database
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
  type: ClusterIP

---

apiVersion: v1
kind: Service
metadata:
  labels:
    app: webchat-user-database
  name: webchat-user-database
  namespace: webchat
spec:
  selector:
    app: webchat-user-database
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
  type: ClusterIP

---

apiVersion: v1
kind: Service
metadata:
  labels:
    app: webchat-email-database
  name: webchat-email-database
  namespace: webchat
spec:
  selector:
    app: webchat-email-database
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
  type: ClusterIP

---

apiVersion: v1
kind: Service
metadata:
  labels:
    app: webchat-image-database
  name: webchat-image-database
  namespace: webchat
spec:
  selector:
    app: webchat-image-database
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
  type: ClusterIP


---

apiVersion: v1
kind: Service
metadata:
  labels:
    app: webchat-message-database
  name: webchat-message-database
  namespace: webchat
spec:
  selector:
    app: webchat-message-database
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
  type: ClusterIP