apiVersion: apps/v1
kind: Deployment

metadata:
  labels:
    app: webchat-auth
  name: webchat-auth
  namespace: webchat
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webchat-auth
  template:
    metadata:
      labels:
        app: webchat-auth
    spec:
      containers:
        - name: webchat-auth
          image: harllemnascimento/rc-auth:v1
          imagePullPolicy: Always
          env:
            - name: PORT
              value: "8080"

            - name: DB_NAME
              value: webchat-auth

            - name: DB_HOST
              value: webchat-auth-database

            - name: DB_PORT
              value: "3306"

            - name : RABBITMQ_HOST
              value: "webchat-rabbitmq"

            - name : USER_SERVICE
              value: "webchat-svc-user"

            - name: JWT_SECRET
              valueFrom: 
                secretKeyRef:
                  name: secrets
                  key: jwt-secret

            - name : DB_USERNAME
              value: "root"

            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: secrets
                  key: db-root-pass
                  
            - name: EMAIL_SENDER
              valueFrom:
                secretKeyRef:
                  name: secrets
                  key: email-sender
          ports:
            - containerPort: 8080
          resources:
            limits:
              memory: "1Gi"
              cpu: "1"
            requests:
              memory: "500Mi"
              cpu: "0.5"