apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: webchat-frontend
  name: webchat-frontend
  namespace: webchat
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webchat-frontend
  template:
    metadata:
      labels:
        app: webchat-frontend
    spec:
      containers:
        - name: webchat-frontend
          image: harllemnascimento/rc-frontend:v1
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
          resources:
            limits:
              memory: "500M"
              cpu: "150m"
            requests:
              memory: "250M"
              cpu: "50m"