apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: webchat-api-gateway
  name: webchat-api-gateway
  namespace: webchat
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webchat-api-gateway
  template:
    metadata:
      labels:
        app: webchat-api-gateway
    spec:
      containers:
        - name: webchat-api-gateway
          image: harllemnascimento/rc-gateway:v1
          imagePullPolicy: Always
          env:
            - name: PORT
              value: "8080"

            - name: USER_SERVICE
              value: "webchat-svc-user"

            - name: AUTH_SERVICE
              value: "webchat-svc-auth"

            - name: MESSAGE_SERVICE
              value: "webchat-svc-message"

            - name: GLOBAL_TIMEOUT
              value: "60000"

            - name: CORS_HOSTS
              value: "http://192.168.49.2:30001,http://192.168.0.101:30001,http://localhost:30001,http://localhost:3000"
              
            - name: JWT_SECRET
              valueFrom: 
                secretKeyRef:
                  name: secrets
                  key: jwt-secret
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 5
          resources:
            limits:
              memory: "500M"
              cpu: "500m"
            requests:
              memory: "250M"
              cpu: "200m"