apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: webchat-image-worker
  name: webchat-image-worker
  namespace: webchat
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webchat-image-worker
  template:
    metadata:
      labels:
        app: webchat-image-worker
    spec:
      containers:
        - name: webchat-image-worker
          image: harllemnascimento/rc-image-worker:v1
          imagePullPolicy: Always
          env:
            - name: PORT
              value: "8080"

            - name: DB_NAME
              value: webchat-image

            - name: DB_HOST
              value: webchat-image-database

            - name: DB_PORT
              value: "3306"

            - name : RABBITMQ_HOST
              value: "webchat-rabbitmq"

            - name : USER_SERVICE
              value: "webchat-svc-user"

            - name : DB_USERNAME
              value: "root"

            - name : IMAGES_FOLDER
              value: "/app/profile-images/"

            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: secrets
                  key: db-root-pass
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 5
          volumeMounts:
            - name: image-volume
              mountPath: /app/profile-images
          resources:
            limits:
              memory: "1Gi"
              cpu: "1000m"
            requests:
              memory: "250M"
              cpu: "200m"
      volumes:
        - name: image-volume
          persistentVolumeClaim:
            claimName: profile-images-pvc