apiVersion: apps/v1
kind: Deployment

metadata:
  labels:
    app: webchat-user
  name: webchat-user
  namespace: webchat
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webchat-user
  template:
    metadata:
      labels:
        app: webchat-user
    spec:
      containers:
        - name: webchat-user
          image: harllemnascimento/rc-user:v1
          imagePullPolicy: Always
          env:
            - name: PORT
              value: "8080"

            - name: DB_NAME
              value: webchat-user

            - name: DB_HOST
              value: webchat-user-database

            - name: DB_PORT
              value: "3306"

            - name : RABBITMQ_HOST
              value: "webchat-rabbitmq"

            - name : IMAGE_SERVICE
              value: "webchat-svc-image-worker"

            - name : AUTH_SERVICE
              value: "webchat-svc-auth"

            - name : DB_USERNAME
              value: "root"

            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: secrets
                  key: db-root-pass

            - name: EMAIL_SENDER
              valueFrom:
                secretKeyRef:
                  name: secrets
                  key: email-sender
                  
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 5
          resources:
            limits:
              memory: "500M"
              cpu: "1000m"
            requests:
              memory: "250M"
              cpu: "200m"