version: "3.8"

services:
  rabbitmq:
    container_name: "rabbitmq-server"
    image: rabbitmq:3.9.7-management
    ports:
      - 5672:5672
      - 15672:15672
      - 45806:15672
    restart: always
    environment:
      - RABBITMQ_USER=guest
      - RABBITMQ_PASSWORD=guest
    networks:
      - rabbitmq-server-net

networks:
  rabbitmq-server-net: {} 

