apiVersion: v1
kind: Service
metadata:
  labels:
    app: webchat-auth
  name: webchat-svc-auth
  namespace: webchat
spec:
  selector:
    app: webchat-auth
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP