apiVersion: v1
kind: Service
metadata:
  labels:
    app: webchat-frontend
  name: webchat-frontend
  namespace: webchat
spec:
  selector:
    app: webchat-frontend
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  type: ClusterIP