apiVersion: v1
kind: Service
metadata:
  labels:
    app: webchat-image-worker
  name: webchat-svc-image-worker
  namespace: webchat
spec:
  selector:
    app: webchat-image-worker
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP