apiVersion: v1
kind: Service
metadata:
  labels:
    app: webchat-proxy
  name: webchat-proxy
  namespace: webchat
spec:
  selector:
    app: webchat-proxy
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30001
  type: NodePort