apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: webchat-rabbitmq
  name: rabbitmq-pvc
  namespace: webchat
spec:
  accessModes:
    - "ReadWriteOnce"
  resources:
    requests:
      storage: "1Gi"