version: '3'

services:
  mq:
    image: vromero/activemq-artemis:latest
    environment:
      - ARTEMIS_USERNAME=artemis
      - ARTEMIS_PASSWORD=artemis
    ports:
      - 8161:8161
      - 61616:61616